title: "(diplo-modulo-1 Book Title)"
copyright: '(diplo-modulo-1 2026), (diplo-modulo-1 Leonardo Heis)'
author: '(diplo-modulo-1 Leonardo Heis)'

execute:
  execute_notebooks: "force"

html:
  use_edit_page_button : true
  use_repository_button: true
  baseurl              : (https://diplo-modulo-1.github.io/diplo-modulo-1/)

repository:
  url: (https://github.com/leonardoheis/diplo-module-1)
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url    : "https://colab.research.google.com"
  thebe        : true

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath


bibtex_bibfiles:
  - bibliography.bib

sphinx:
  config:
    bibtex_reference_style: author_year
