name: Build PDF of the Book

on:
  push:
    branches: source

  workflow_dispatch:
  repository_dispatch:

jobs:
  pdf_from_latex:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.02

    - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
      with:
        python-version: 3.12

    - name: Install dependencies
      run: uv sync --all-groups

    - name: Install latex dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y     \
          texlive-latex-recommended \
          texlive-latex-extra       \
          texlive-fonts-extra       \
          fonts-freefont-otf        \
          texlive-xetex             \
          latexmk                   \
          xindy

    - name: Build PDF from LaTeX
      run: uv run jb build book --builder pdflatex --path-output .

    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
      with:
        name: Book PDF
        path: _build/latex/book.pdf
